version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "athena"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-mx9861lv18es"
s3_prefix = "athena"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
